---
title: "Yang Replication"
output: html_document
author: Catalina Burch
---

#This Code replicates the work of Yang et al 2006 to check that our methods are correct

```{r, include=FALSE}
#load libraries
library(readr) 
library(tidyverse)
library(here)
library(taxize)

#load data
raw_stomach_contents <- read_csv(here("data/GOA_Raw_StomachContents.csv"))

```


```{r, include=F}

#Filter for year 1999 and 2001
sc_1999 <- raw_stomach_contents %>% 
  filter(Year == 1999)

sc_2001 <- raw_stomach_contents %>% 
  filter(Year == 2001)

#creating object with scientific names for Predators
pred_names <- raw_stomach_contents %>% 
  distinct(Pred_name)

pred_list<-(sci2comm(pred_names$Pred_name, simplify = T, db = "ncbi"))
pred_names_df <- rownames_to_column(as.data.frame(do.call(rbind, pred_list)))
colnames(pred_names_df) <- c("Pred_name", "Com_name")

#merging common names with overall dataframe
stomach_contents <- full_join(raw_stomach_contents, pred_names_df, by = "Pred_name")

```

Recreating Table 1

```{r Table 1, echo=FALSE}
#Calculating Summary Stats
#Empty stomachs
E_1999 <- sc_1999 %>% 
  filter(Pred_stomwt == 0) %>% 
  group_by(Pred_name) %>% 
  summarise(E = n())

#Full stomachs
F_1999 <- sc_1999 %>% 
  filter(Pred_stomwt>0) %>% 
  group_by(Pred_name) %>% 
  summarise(F = n())

#Total stomachs, mean length and stdv 
T_1999 <- sc_1999 %>% 
  group_by(Pred_name) %>% 
  summarise(T = n(), "max" = max(Pred_len), "min" = min(Pred_len),
            "Fork length (cm)* Mean" = mean(Pred_len),
            "SD" = sd(Pred_len)) %>% 
  mutate(year = 1999)

#Combining into one table
FE_1999 <- full_join(F_1999, E_1999, by = "Pred_name")

FET_1999 <- full_join(FE_1999, T_1999, by = "Pred_name")

#Warning: this section is slow to run
#Finding Scientific Names
list<-(sci2comm(FET_1999$Pred_name, simplify = T))
names <- rownames_to_column(as.data.frame(do.call(rbind, list)))
colnames(names) <- c("Pred_name", "Com_nam")

#Adding common names to final table
Table1_1999 <- full_join(names, FET_1999, by = "Pred_name")

Table1_1999 

write.csv(Table1_1999, file = here("output/table11_1999.csv"))

#Unfortunately this table does not match

```


#Recreating Table 2
```{r Table2}
#Calculating Summary Stats
#Empty stomachs
E_2001 <- sc_2001 %>% 
  filter(Pred_stomwt == 0) %>% 
  group_by(Pred_name) %>% 
  summarise(E = n())

#Full stomachs
F_2001 <- sc_2001 %>% 
  filter(Pred_stomwt>0) %>% 
  group_by(Pred_name) %>% 
  summarise(F = n())

#Total stomachs, mean length and stdv 
T_2001 <- sc_2001 %>% 
  group_by(Pred_name) %>% 
  summarise(T = n(), "max" = max(Pred_len), "min" = min(Pred_len),
            "Fork length (cm)* Mean" = mean(Pred_len),
            "SD" = sd(Pred_len)) %>% 
  mutate(year = 2001)

#Combining into one table
FE_2001 <- full_join(F_2001, E_2001, by = "Pred_name")

FET_2001 <- full_join(FE_2001, T_2001, by = "Pred_name")

#Finding Scientific Names
#WARNING: this is slow to run
list<-(sci2comm(FET_2001$Pred_name, simplify = T))
names <- rownames_to_column(as.data.frame(do.call(rbind, list)))
colnames(names) <- c("Pred_name", "Com_nam")

#Adding common names to final table
Table2_2001 <- full_join(names, FET_2001, by = "Pred_name")

Table2_2001

write.csv(Table2_2001, file = here("output/table2_2001.csv"))


```



Creating tables for the other years and then joining into one big spreadsheet
```{r summary tables}
#These are the years not included in Yang et al: 2003 2005 2007 2009 2011 2013 2015 2017 2019 

############YEAR 2003
E_2003 <- sc_2003 %>% 
  filter(Pred_stomwt == 0) %>% 
  group_by(Pred_name) %>% 
  summarise(E = n())

#Full stomachs
F_2003 <- sc_2001 %>% 
  filter(Pred_stomwt>0) %>% 
  group_by(Pred_name) %>% 
  summarise(F = n())

#Total stomachs, mean length and stdv 
T_2001 <- sc_2001 %>% 
  group_by(Pred_name) %>% 
  summarise(T = n(), "max" = max(Pred_len), "min" = min(Pred_len),
            "Fork length (cm)* Mean" = mean(Pred_len),
            "SD" = sd(Pred_len)) %>% 
  mutate(year = 2001)

#Combining into one table
FE_2001 <- full_join(F_2001, E_2001, by = "Pred_name")

FET_2001 <- full_join(FE_2001, T_2001, by = "Pred_name")

#Finding Scientific Names
#WARNING: this is slow to run
list<-(sci2comm(FET_2001$Pred_name, simplify = T))
names <- rownames_to_column(as.data.frame(do.call(rbind, list)))
colnames(names) <- c("Pred_name", "Com_nam")

#Adding common names to final table
Table2_2001 <- full_join(names, FET_2001, by = "Pred_name")





```







